#!/usr/bin/env sh

# ===== Rules ==================================
#yabai -m rule --add app!="not_my_app" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="Rofi" app="^choose$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
#yabai -m rule --add label="GIMP-2.10" app="^GIMP-2.10$" manage=off
#yabai -m rule --add label="Skim" app="^Skim$" manage=off
yabai -m rule --add label="Anki" app="^Anki$" manage=off
yabai -m rule --add label="Digital Color Meter" app="^Digital Color Meter$" manage=off

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_border                off
yabai -m config split_ratio                  0.6
yabai -m config auto_balance                 off
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       float
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20
yabai -m config external_bar all:20:60

yabai -m config window_border off
yabai -m config window_border_width 3
yabai -m config active_window_border_color 0xFFF4A66E
#yabai -m config active_window_border_color 0xFFFF9933
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config insert_feedback_color      0xffd75f5f

yabai -m config window_shadow on
yabai -m config window_topmost off

# Sketchybar event signals
#yabai -m signal --add event=window_created action="sketchybar -m --trigger window_created &> /dev/null"
#yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_destroyed &> /dev/null"
#yabai -m signal --add event=space_changed action="~/.config/sketchybar/plugins/yabai_spaces.js --update &"
yabai -m signal --add event=space_changed action="~/.config/yabai/toggle_outline.bash"
yabai -m signal --add event=space_changed action="~/.config/sketchybar/plugins/yabai_spaces.js --refresh"

rm ~/.config/yabai/pinned_windows.json
~/.config/sketchybar/plugins/yabai_spaces.js --update
